name: CI/CD

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install -Dproject.version=${{ github.sha }}

  deploy-development:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure App Service
        run: |
          # Tutaj dodaj skrypty/operacje, które są potrzebne do wdrożenia na środowisko production
          # Przykładowo, możesz użyć Azure CLI lub innego narzędzia do wdrożenia aplikacji na środowisko production
      

  deploy-production:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production
        run: |
          # Tutaj dodaj skrypty/operacje, które są potrzebne do wdrożenia na środowisko production
          # Przykładowo, możesz użyć Azure CLI lub innego narzędzia do wdrożenia aplikacji na środowisko production


