name: CI/CD

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Increment version
        if: github.event_name == 'push'
        run: |
          current_version=$(grep 'application.version' src/main/resources/application.properties | cut -d'=' -f2)
          echo "Current version: $current_version"
          current_version=$(grep 'application.version' src/main/resources/application.properties | cut -d'=' -f2)
          new_version=$((current_version + 1))
          sed -i "s/application.version=$current_version/application.version=$new_version/" src/main/resources/application.properties
          echo "New version: $new_version"
          cat src/main/resources/application.properties
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/main/resources/application.properties
          git commit -m "Increment application version"
          git push

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'


  production:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'mwopipeline'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A26ABEDC7C5E4F25960DA5BB9C248838 }}
          package: '*.jar'

  development:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'productionmwo'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_65F2292AE65F4EAE9CEEDEB5D615BA35 }}
          package: '*.jar'