name: CI/CD

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install -Dproject.version=${{ github.sha }}

  deploy-development:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        if: runner.os == 'Linux'
      - name: Log in to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      - name: Deploy to Azure App Service
        run: az webapp deployment source config-zip --resource-group YourResourceGroup --name YourAppName --src target/your-app.jar
      

  deploy-production:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production
        run: |
          # Tutaj dodaj skrypty/operacje, które są potrzebne do wdrożenia na środowisko production
          # Przykładowo, możesz użyć Azure CLI lub innego narzędzia do wdrożenia aplikacji na środowisko production


